import '@/css/vazirmatn.css';
import '@/css/style.css';

import type { Metadata } from 'next';

import { Toaster } from 'sonner';

import { TRPCReactProvider } from '@/trpc/client';
import { Providers } from './providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TRPCReactProvider>
      <html dir='rtl' lang='ar' suppressHydrationWarning>
        <body className='antialiased'>
          <Toaster />
          <Providers>{children}</Providers>
        </body>
      </html>
    </TRPCReactProvider>
  );
}
